MIN_MA_WINDOW_SZ = 10  # Moving average window size
MIN_MULTIPLIER = 4  # minimum multiplication factor used in filter 4
IF_N_ESTIMATORS = 100  # used in Isolation classifier
IF_CONTAMINATION = 0.01  # used in Isolation classifier
IF_MAX_FEATURES = 5  # used in Isolation classifier
THRESHOLD_Y_NOISE_LVL5 = 30  # threshold for filtering out too near-in-y flares
THRESHOLD_X_NOISE_LVL5 = 500  # threshold for filtering out too near-in-x flares
MAX_WINDOW_SIZE = 120  # max window size used in moving average
MIN_WINDOW_SIZE = 100  # min  window size used in moving average
MINIMUM_DATAPOINTS_IN_GTI = 120  # minimum data points needed in discontinuous intervals
SIGMOID_SHIFT_WINDOW_SIZE = 240  # window size origin shift for sigmoid
